name: Continuous Integration / Deployment
on: push
jobs:
  test:
    name: Build, Lint and Test the Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint Project
        run: npm run lint
      - name: Test Project
        run: npm test
      - name: Build Project
        run: npm run build
